### ISSUE TITLE
segv cd without HOME

### ISSUE THREAD

**Issue by massahito** [libknt/minishell_part2#58]
flow

 $ env -i ./minishell
minishell>cd /etc/
HOME not set
minishell>cd /etc/
HOME not set
minishell>cd /etc/
HOME not set
minishell>pwd
/Users/marai/Documents/minishell
minishell>echo $HOME

minishell>export HOME=/Users/marai
minishell>cd
zsh: segmentation fault  env -i ./minishell

**Comment by ghost** [comment]
直しました。
