### ISSUE TITLE
leak

### ISSUE THREAD

**Issue by libknt** [libknt/minishell_part2#69]
./minishell 
minishell>unset
unset: not enough arguments

minishell:unset: command not found
minishell>unset
unset: not enough arguments

minishell:unset: command not found
minishell>unset
unset: not enough arguments

minishell:unset: command not found
minishell>unset
unset: not enough arguments

minishell:unset: command not found
minishell>unset
unset: not enough arguments

minishell:unset: command not found
minishell>ls | unset
unset: not enough arguments

minishell>

=================================================================
==5648==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f3fcd2d0867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55be4fa48c1d in ft_calloc (/app/minishell/minishell+0x15c1d)
    #2 0x55be4fa3c9d5 in new_status (/app/minishell/minishell+0x99d5)
    #3 0x55be4fa3cc93 in buildin (/app/minishell/minishell+0x9c93)
    #4 0x55be4fa4165e in exec_fork (/app/minishell/minishell+0xe65e)
    #5 0x55be4fa41a8d in exec (/app/minishell/minishell+0xea8d)
    #6 0x55be4fa43af9 in exec_tree (/app/minishell/minishell+0x10af9)
    #7 0x55be4fa43d7f in exe_ (/app/minishell/minishell+0x10d7f)
    #8 0x55be4fa487bd in func_readline (/app/minishell/minishell+0x157bd)
    #9 0x55be4fa489bd in main (/app/minishell/minishell+0x159bd)
    #10 0x7f3fccfc9d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: 24 byte(s) leaked in 1 allocation(s).
minishell>

**Comment by ghost** [comment]
完了
