### ISSUE TITLE
minishell> <aでleak

### ISSUE THREAD

**Issue by massahito** [libknt/minishell_part2#72]
>minishell> <a
で
=================================================================
==27306==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fc7816b4867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5562080f8d2b in ft_calloc (/home/masahitoarai/Documents/minishell/minishell+0x16d2b)
    #2 0x5562080f34e5 in new_fd (/home/masahitoarai/Documents/minishell/minishell+0x114e5)
    #3 0x5562080f36a9 in open_file (/home/masahitoarai/Documents/minishell/minishell+0x116a9)
    #4 0x5562080f3e01 in redirect_left (/home/masahitoarai/Documents/minishell/minishell+0x11e01)
    #5 0x5562080f3322 in redirect_check (/home/masahitoarai/Documents/minishell/minishell+0x11322)
    #6 0x5562080f19f2 in exe_ (/home/masahitoarai/Documents/minishell/minishell+0xf9f2)
    #7 0x5562080f6666 in func_readline (/home/masahitoarai/Documents/minishell/minishell+0x14666)
    #8 0x5562080f6866 in main (/home/masahitoarai/Documents/minishell/minishell+0x14866)
    #9 0x7fc781229d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 16 byte(s) leaked in 1

**Comment by ghost** [comment]
お疲れ様

**Comment by ghost** [comment]
./minishell
minishell> <a
minishell > cat <a
でまだleakしている模様。

**Comment by ghost** [comment]
ありがとうございました！
