### ISSUE TITLE
leak

### ISSUE THREAD

**Issue by libknt** [libknt/minishell_part2#78]
root@d08dfd9f8c95:/app/minishell# ./minishell 
minishell>ls
Makefile  include  leak.sh  libmshell  loop.sh  minishell  obj  print.c  result  srcs  test.sh  test2.sh
minishell>Cat 
minishell:Cat: command not found
minishell>cat <a
minishell:a: No such file or directory
minishell><a
minishell:a: No such file or directory
minishell>cat <ac  gera> feargae ga  
minishell:ac: No such file or directory
minishell>cat <Makefile  gera> feargae ga  
/usr/bin/cat: gera: No such file or directory
/usr/bin/cat: ga: No such file or directory
minishell>

minishell>

=================================================================
==13699==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fdccb8b5867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7fdccb7e6bac in xmalloc (/lib/x86_64-linux-gnu/libreadline.so.8+0x39bac)

SUMMARY: AddressSanitizer: 32 byte(s) leaked in 1 allocation(s).

**Comment by ghost** [comment]
ありがとうございました！
