### ISSUE TITLE
env cdasiubve

### ISSUE THREAD

**Issue by libknt** [libknt/minishell_part2#92]
kyoda@c1r21s1:~/Desktop/minishell$ env -i ./minishell 
minishell>env
minishell>export
declare -x OLDPWD
minishell>unset OLDPWD
minishell>export
minishell>export PWD
minishell>env
minishell>export
declare -x PWD
minishell>export PWD="kfjsdklfj"
minishell>export                
declare -x PWD="kfjsdklfj"
minishell>env                   
PWD=kfjsdklfj
minishell>unset PWD | unset PWD
minishell>export
declare -x PWD="kfjsdklfj"
minishell>env fjaksdkf
minishell:fjaksdkf: command not found
minishell(24051,0x10b91f5c0) malloc: *** error for object 0x7f8babc03358: pointer being freed was not allocated
minishell(24051,0x10b91f5c0) malloc: *** set a breakpoint in malloc_error_break to debug

**Comment by ghost** [comment]
終わりました。
